/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Faculty;

import Dean.DashboardDean;
import Home.Dashboard;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Cursor;

/**
 *
 * @author Jaden
 */
public class DashboardFaculty extends javax.swing.JFrame {

    /**
     * Creates new form DashboardFaculty
     */
    final String DB_URL = "jdbc:sqlserver://localhost\\DESKTOP-FT3D7QK:1433;databaseName=enrollment;encrypt=true;trustServerCertificate=true";
    final String USERNAME = "admin";
    final String PASSWORD = "admin";
    static int userSessionId;
    boolean isDean = false;

    public DashboardFaculty(int userSessionId) {
        initComponents();
        this.userSessionId = userSessionId;

        {
            btnBack.setOpaque(false); // Make the button transparent
            btnBack.setContentAreaFilled(false); // Don't fill the button area with background
            btnBack.setBorderPainted(false); // Remove the default button border
            btnBack.setForeground(Color.WHITE); // Set text color
            btnBack.setFocusPainted(false); // Remove focus border
            btnBack.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Set cursor
        }
        {
            btnSubject.setOpaque(false); // Make the button transparent
            btnSubject.setContentAreaFilled(false); // Don't fill the button area with background
            btnSubject.setBorderPainted(false); // Remove the default button border
            btnSubject.setForeground(Color.WHITE); // Set text color
            btnSubject.setFocusPainted(false); // Remove focus border
            btnSubject.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Set cursor
        }
        {
            btnDean.setOpaque(false); // Make the button transparent
            btnDean.setContentAreaFilled(false); // Don't fill the button area with background
            btnDean.setBorderPainted(false); // Remove the default button border
            btnDean.setForeground(Color.WHITE); // Set text color
            btnDean.setFocusPainted(false); // Remove focus border
            btnDean.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Set cursor
        }

        try {
            Connection conn = DriverManager.getConnection(DB_URL, USERNAME, PASSWORD);
            
            String sqlUserType = "select UserType from ACCOUNT where UserID = ?";
            PreparedStatement preparedStatementUserType = conn.prepareStatement(sqlUserType);
            preparedStatementUserType.setInt(1, userSessionId);
            ResultSet resultSetUserType =preparedStatementUserType.executeQuery();

            if (resultSetUserType.next()) {
                if(resultSetUserType.getString("UserType").equalsIgnoreCase("dean")){
                    isDean = true;;
                }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error deleting account: " + e.getMessage());
        }
        
        if(!isDean){
            btnDean.setEnabled(false);
            btnDean.setFocusable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnSubject = new javax.swing.JButton();
        btnDean = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Faculty Dashboard");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackMousePressed(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 73, 30, 30));

        btnSubject.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 2, true));
        btnSubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubjectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubjectMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSubjectMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSubjectMouseReleased(evt);
            }
        });
        btnSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubjectActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 270, 245, 271));

        btnDean.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 2, true));
        btnDean.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDeanMousePressed(evt);
            }
        });
        btnDean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeanActionPerformed(evt);
            }
        });
        getContentPane().add(btnDean, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 270, 245, 271));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 135, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg_DashboardFaculty.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubjectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubjectMouseEntered
        btnSubject.setBorderPainted(true);
    }//GEN-LAST:event_btnSubjectMouseEntered

    private void btnSubjectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubjectMouseExited
        btnSubject.setBorderPainted(false);
    }//GEN-LAST:event_btnSubjectMouseExited

    private void btnSubjectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubjectMousePressed
        btnSubject.setContentAreaFilled(true);
    }//GEN-LAST:event_btnSubjectMousePressed

    private void btnSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubjectActionPerformed
        new FacultySubject(userSessionId).setVisible(true);
    }//GEN-LAST:event_btnSubjectActionPerformed

    private void btnDeanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeanMouseEntered
        if(isDean)
            btnDean.setBorderPainted(true);
    }//GEN-LAST:event_btnDeanMouseEntered

    private void btnDeanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeanMouseExited
        btnDean.setBorderPainted(false);
    }//GEN-LAST:event_btnDeanMouseExited

    private void btnDeanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeanMousePressed
        if(isDean)
        btnDean.setContentAreaFilled(true);
    }//GEN-LAST:event_btnDeanMousePressed

    private void btnDeanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeanActionPerformed
        if(isDean){
            new DashboardDean(userSessionId).setVisible(true);
            this.dispose();
        }  
    }//GEN-LAST:event_btnDeanActionPerformed

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        btnBack.setBorderPainted(true);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        btnBack.setBorderPainted(false);
    }//GEN-LAST:event_btnBackMouseExited

    private void btnBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMousePressed
        btnBack.setContentAreaFilled(true);
    }//GEN-LAST:event_btnBackMousePressed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new Dashboard(userSessionId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubjectMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubjectMouseReleased
        btnSubject.setContentAreaFilled(false);
    }//GEN-LAST:event_btnSubjectMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardFaculty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardFaculty(userSessionId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDean;
    private javax.swing.JButton btnSubject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
