package Home;

//import Authentication.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jaden
 */
import Authentication.LoginPage;
import java.awt.*;

public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    final String DB_URL = "jdbc:sqlserver://localhost\\DESKTOP-FT3D7QK:1433;databaseName=enrollment;encrypt=true;trustServerCertificate=true";
    final String USERNAME = "admin";
    final String PASSWORD = "admin";
    String enrollmentStatus;
    static int userSessionID;

    public HomePage(int userSessionID) {
        initComponents();
        {
            btnDashboard.setOpaque(false); // Make the button transparent
            btnDashboard.setContentAreaFilled(false); // Don't fill the button area with background
            btnDashboard.setBorderPainted(false); // Remove the default button border
            btnDashboard.setForeground(Color.WHITE); // Set text color
            btnDashboard.setFocusPainted(false); // Remove focus border
            btnDashboard.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Set cursor
        }
        {
            btnLogout.setOpaque(false); // Make the button transparent
            btnLogout.setContentAreaFilled(false); // Don't fill the button area with background
            btnLogout.setBorderPainted(false); // Remove the default button border
            btnLogout.setForeground(Color.WHITE); // Set text color
            btnLogout.setFocusPainted(false); // Remove focus border
            btnLogout.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Set cursor
        }
        {
            btnAcademics.setOpaque(false); // Make the button transparent
            btnAcademics.setContentAreaFilled(false); // Don't fill the button area with background
            btnAcademics.setBorderPainted(false); // Remove the default button border
            btnAcademics.setForeground(Color.WHITE); // Set text color
            btnAcademics.setFocusPainted(false); // Remove focus border
            btnAcademics.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Set cursor
        }
        {
            btnAboutBulsu.setOpaque(false); // Make the button transparent
            btnAboutBulsu.setContentAreaFilled(false); // Don't fill the button area with background
            btnAboutBulsu.setBorderPainted(false); // Remove the default button border
            btnAboutBulsu.setForeground(Color.WHITE); // Set text color
            btnAboutBulsu.setFocusPainted(false); // Remove focus border
            btnAboutBulsu.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Set cursor
        }
        this.userSessionID = userSessionID;
        jLabel2.setText("ID IS " + HomePage.userSessionID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnAboutBulsu = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();
        btnAcademics = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        btnAboutBulsu.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnAboutBulsu.setText("ABOUT BULSU");
        btnAboutBulsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutBulsuActionPerformed(evt);
            }
        });
        getContentPane().add(btnAboutBulsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 98, -1, -1));

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 98, -1, -1));

        btnDashboard.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnDashboard.setText("DASHBOARD");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        getContentPane().add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 98, -1, -1));

        btnAcademics.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnAcademics.setText("ACADEMICS");
        btnAcademics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcademicsActionPerformed(evt);
            }
        });
        getContentPane().add(btnAcademics, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 98, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg_HomePage.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        new LoginPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAcademicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcademicsActionPerformed
        new AcademicsPage(userSessionID).setVisible(true);
        this.dispose();
        
        /*try {
            Connection conn = DriverManager.getConnection(DB_URL, USERNAME, PASSWORD);

            String sqlEnrollmentStatus = "SELECT EnrollmentStatus FROM STUDENT WHERE UserID = ?";
            PreparedStatement preparedStatementEnrollmentStatus = conn.prepareStatement(sqlEnrollmentStatus);
            preparedStatementEnrollmentStatus.setInt(1, userSessionID);
            ResultSet resultSetEnrollmentStatus = preparedStatementEnrollmentStatus.executeQuery();

            if (resultSetEnrollmentStatus.next()) {
                enrollmentStatus = resultSetEnrollmentStatus.getString("EnrollmentStatus");
                if (!enrollmentStatus.equalsIgnoreCase("enrolled")) {
                    new step1_enroll(userSessionID).setVisible(true);
                    this.dispose();
                }else{
                    new step5_enroll(userSessionID).setVisible(true);
                    this.dispose();
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }*/
    }//GEN-LAST:event_btnAcademicsActionPerformed

    private void btnAboutBulsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutBulsuActionPerformed
        new AboutBulsuPage(userSessionID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAboutBulsuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage(userSessionID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAboutBulsu;
    private javax.swing.JButton btnAcademics;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
