package Enrollment;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author acer
 */
public class step3_enroll extends javax.swing.JFrame {

    /**
     * Creates new form step3_enroll
     */
    final String DB_URL = "jdbc:sqlserver://localhost\\DESKTOP-FT3D7QK:1433;databaseName=enrollment;encrypt=true;trustServerCertificate=true";
    final String USERNAME = "admin";
    final String PASSWORD = "admin";
    static String selectedCourse, curriculum, campus, courseID, courseName, section;
    static int userSessionID, yearLevel, studentID;
    static List<String> enrolledCode = new ArrayList<>();

    // Get values for student enrollment
    public step3_enroll(int userSessionID, String selectedCourse, String curriculum, String campus, String courseID, String courseName, String section, List<String> enrolledCode, int yearLevel) {
        initComponents();
        this.userSessionID = userSessionID;
        this.selectedCourse = selectedCourse;
        this.curriculum = curriculum;
        this.campus = campus;
        this.courseID = courseID;
        this.courseName = courseName;
        this.section = section;
        this.enrolledCode = enrolledCode;
        this.yearLevel = yearLevel;

        System.out.println("step 3" + enrolledCode);
        System.out.println(campus);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Automatic assessment process.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Proceeding will confirm your enrollment.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Please review your details now.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnBack.png"))); // NOI18N
        btnBack.setOpaque(true);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 616, 40, -1));

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnNext.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 616, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg_Step3Enroll.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new step2_enroll(userSessionID, selectedCourse, curriculum, campus, courseID, courseName, section, enrolledCode, yearLevel).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    // Enrolls student
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        
        try {
            Connection conn = DriverManager.getConnection(DB_URL, USERNAME, PASSWORD);
            // Succesfully connected to database...

            String sqlStudentInfo = "SELECT * FROM STUDENT where UserID = ?";
            PreparedStatement preparedStatementStudent = conn.prepareStatement(sqlStudentInfo);
            preparedStatementStudent.setInt(1, userSessionID);
            ResultSet resultSetStudentInfo = preparedStatementStudent.executeQuery();

            if (resultSetStudentInfo.next()) {
                studentID = resultSetStudentInfo.getInt("StudID");
            }

            // Insert enrolled subject
            String sqlEnrolledSubject = "INSERT INTO ENROLLED_SUBJECT (StudID, SubjectCode)"
                    + "VALUES (?, ?)";
            for (String subjectCode : enrolledCode) {
                PreparedStatement preparedStatementEnrolledSubject = conn.prepareStatement(sqlEnrolledSubject, new String[]{"EnrolledSubjectID"});
                preparedStatementEnrolledSubject.setInt(1, studentID);
                preparedStatementEnrolledSubject.setString(2, subjectCode);

                int rowsInserted = preparedStatementEnrolledSubject.executeUpdate();

                if (rowsInserted > 0) {
                    System.out.println("ENROLLMENT_SUBJECT table success" + subjectCode);
                }
            }

            /*{String sqlEnrolledSubject = "INSERT INTO ENROLLED_SUBJECT (Section, StudID, SubjectCode)"
                    + "VALUES (?, ?, ?)";
            PreparedStatement preparedStatementEnrolledSubject = conn.prepareStatement(sqlEnrolledSubject, new String[]{"EnrolledSubjectID"});
            preparedStatementEnrolledSubject.setString(1, section);
            preparedStatementEnrolledSubject.setInt(2, userSessionID);
            preparedStatementEnrolledSubject.setString(3, enrolledCode.getFirst());

            int rowsInserted = preparedStatementEnrolledSubject.executeUpdate();
            
            if (rowsInserted > 0) {
                ResultSet generatedKeys = preparedStatementEnrolledSubject.getGeneratedKeys();
                System.out.println("Successful insertion of subject!@!@#");
                if (generatedKeys.next()) {
                    int enrollmentId = generatedKeys.getInt(1);
                    String sqlName = "INSERT INTO ENROLLED_SUBJECT (EnrolledSubjectID, Section, StudID, SubjectCode)";
                    for (int i = 1; i < enrolledCode.size(); i++) {
                        String subjectCode = enrolledCode.get(i);
                        
                        preparedStatementEnrolledSubject.setInt(1, enrollmentId);
                        preparedStatementEnrolledSubject.setString(2, section);
                        preparedStatementEnrolledSubject.setInt(3, userSessionID);
                        preparedStatementEnrolledSubject.setString(4, subjectCode);
                    }
                }
            }*/
            // Get the current date and time
            LocalDateTime now = LocalDateTime.now();
            // Convert LocalDateTime to java.sql.Timestamp
            Timestamp currentTimestamp = Timestamp.valueOf(now);

            // Set enrollment status
            String sqlEnrollmentStatus = "INSERT INTO ENROLLMENT (EnrollmentDate, StudID, CourseID)"
                    + "VALUES (?, ?, ?)";
            PreparedStatement preparedStatementEnrollmentStatus = conn.prepareStatement(sqlEnrollmentStatus);
            preparedStatementEnrollmentStatus.setTimestamp(1, currentTimestamp);
            preparedStatementEnrollmentStatus.setInt(2, studentID);
            preparedStatementEnrollmentStatus.setString(3, courseID);

            int rowsInserted = preparedStatementEnrollmentStatus.executeUpdate();

            if (rowsInserted > 0) {
                System.out.println("ENROLLMENT table success");

                String sqlInsertLog = "insert into USER_LOG (UserID, UserAction, ActionDate) values (?,?,?)";
                PreparedStatement preparedStatementInsertLog = conn.prepareStatement(sqlInsertLog);
                preparedStatementInsertLog.setInt(1, userSessionID);
                preparedStatementInsertLog.setString(2, "Student enrolled");
                preparedStatementInsertLog.setTimestamp(3, currentTimestamp);

                int insertedRow = preparedStatementInsertLog.executeUpdate();
                if (insertedRow > 0) {
                    System.out.println("User log updated");
                }
            }

            // Updates student status
            String sqlStudent = "UPDATE STUDENT SET Section = ?, Campus = ?, CourseID = ?, "
                    + "EnrollmentStatus = ? WHERE UserID = ?";
            PreparedStatement preparedStatementRegister = conn.prepareStatement(sqlStudent);
            preparedStatementRegister.setString(1, section);
            preparedStatementRegister.setString(2, campus);
            preparedStatementRegister.setString(3, courseID);
            preparedStatementRegister.setString(4, "enrolled");
            preparedStatementRegister.setInt(5, userSessionID);

            int rowsUpdatedStudent = preparedStatementRegister.executeUpdate();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        new step4_enroll(userSessionID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(step3_enroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(step3_enroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(step3_enroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(step3_enroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new step3_enroll(userSessionID, selectedCourse, curriculum, campus, courseID, courseName, section, enrolledCode, yearLevel).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
