package Admin;


import Admin.AdminFunctions.AdminInformation;
import Home.Dashboard;
import java.awt.Cursor;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author acer
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form admin0
     */
    static int userSessionID;
    
    public AdminDashboard(int userSessionID) {
        initComponents();
        this.userSessionID = userSessionID;
        {
            btnBack.setOpaque(false); // Make the button transparent
            btnBack.setContentAreaFilled(false); // Don't fill the button area with background
            btnBack.setBorderPainted(false); // Remove the default button border
            btnBack.setFocusPainted(false); // Remove focus border
            btnBack.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Set cursor
        }
        {
            btnAdmins.setOpaque(false); // Make the button transparent
            btnAdmins.setContentAreaFilled(false); // Don't fill the button area with background
            btnAdmins.setBorderPainted(false); // Remove the default button border
            btnAdmins.setFocusPainted(false); // Remove focus border
            btnAdmins.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Set cursor
        }
        {
            btnStudents.setOpaque(false); // Make the button transparent
            btnStudents.setContentAreaFilled(false); // Don't fill the button area with background
            btnStudents.setBorderPainted(false); // Remove the default button border
            btnStudents.setFocusPainted(false); // Remove focus border
            btnStudents.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Set cursor
        }
        {
            btnLogs.setOpaque(false); // Make the button transparent
            btnLogs.setContentAreaFilled(false); // Don't fill the button area with background
            btnLogs.setBorderPainted(false); // Remove the default button border
            btnLogs.setFocusPainted(false); // Remove focus border
            btnLogs.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Set cursor
        }
        {
            btnFaculty.setOpaque(false); // Make the button transparent
            btnFaculty.setContentAreaFilled(false); // Don't fill the button area with background
            btnFaculty.setBorderPainted(false); // Remove the default button border
            btnFaculty.setFocusPainted(false); // Remove focus border
            btnFaculty.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Set cursor
        }
        {
            btnCourse.setOpaque(false); // Make the button transparent
            btnCourse.setContentAreaFilled(false); // Don't fill the button area with background
            btnCourse.setBorderPainted(false); // Remove the default button border
            btnCourse.setFocusPainted(false); // Remove focus border
            btnCourse.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Set cursor
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnAdmins = new javax.swing.JButton();
        btnStudents = new javax.swing.JButton();
        btnLogs = new javax.swing.JButton();
        btnFaculty = new javax.swing.JButton();
        btnCourse = new javax.swing.JButton();
        btnEnrolledSubject = new javax.swing.JButton();
        btnCollege = new javax.swing.JButton();
        btnCourseSubject = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackMousePressed(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 73, 30, 30));

        btnAdmins.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        btnAdmins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdminsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdminsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAdminsMousePressed(evt);
            }
        });
        btnAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminsActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdmins, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 145, 203, 220));

        btnStudents.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        btnStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStudentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStudentsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnStudentsMousePressed(evt);
            }
        });
        btnStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentsActionPerformed(evt);
            }
        });
        getContentPane().add(btnStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 145, 203, 220));

        btnLogs.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        btnLogs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLogsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLogsMouseReleased(evt);
            }
        });
        btnLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogsActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 145, 203, 220));

        btnFaculty.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        btnFaculty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFacultyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFacultyMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFacultyMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnFacultyMouseReleased(evt);
            }
        });
        btnFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacultyActionPerformed(evt);
            }
        });
        getContentPane().add(btnFaculty, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 145, 203, 220));

        btnCourse.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        btnCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCourseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCourseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCourseMouseReleased(evt);
            }
        });
        btnCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseActionPerformed(evt);
            }
        });
        getContentPane().add(btnCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 398, 203, 220));

        btnEnrolledSubject.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        btnEnrolledSubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEnrolledSubjectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEnrolledSubjectMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEnrolledSubjectMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEnrolledSubjectMouseReleased(evt);
            }
        });
        btnEnrolledSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrolledSubjectActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnrolledSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 398, 203, 220));

        btnCollege.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        btnCollege.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCollegeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCollegeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCollegeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCollegeMouseReleased(evt);
            }
        });
        btnCollege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCollegeActionPerformed(evt);
            }
        });
        getContentPane().add(btnCollege, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 398, 203, 220));

        btnCourseSubject.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        btnCourseSubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCourseSubjectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCourseSubjectMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCourseSubjectMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCourseSubjectMouseReleased(evt);
            }
        });
        btnCourseSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseSubjectActionPerformed(evt);
            }
        });
        getContentPane().add(btnCourseSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(908, 398, 203, 220));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg_AdminDashboard.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminsActionPerformed
        new AdminInformation(userSessionID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdminsActionPerformed

    private void btnAdminsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminsMouseEntered
        btnAdmins.setBorderPainted(true);
    }//GEN-LAST:event_btnAdminsMouseEntered

    private void btnAdminsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminsMouseExited
        btnAdmins.setBorderPainted(false);
    }//GEN-LAST:event_btnAdminsMouseExited

    private void btnAdminsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminsMousePressed
        btnAdmins.setContentAreaFilled(true);
    }//GEN-LAST:event_btnAdminsMousePressed

    private void btnStudentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentsMouseEntered
        btnStudents.setBorderPainted(true);
    }//GEN-LAST:event_btnStudentsMouseEntered

    private void btnStudentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentsMouseExited
        btnStudents.setBorderPainted(false);
    }//GEN-LAST:event_btnStudentsMouseExited

    private void btnStudentsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentsMousePressed
        btnStudents.setContentAreaFilled(true);
    }//GEN-LAST:event_btnStudentsMousePressed

    private void btnStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentsActionPerformed
        new StudentInformation(userSessionID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStudentsActionPerformed

    private void btnLogsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogsMouseEntered
        btnLogs.setBorderPainted(true);
    }//GEN-LAST:event_btnLogsMouseEntered

    private void btnLogsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogsMouseExited
        btnLogs.setBorderPainted(false);
    }//GEN-LAST:event_btnLogsMouseExited

    private void btnLogsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogsMousePressed
        btnLogs.setContentAreaFilled(true);
    }//GEN-LAST:event_btnLogsMousePressed

    private void btnLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogsActionPerformed
        new LogView(userSessionID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogsActionPerformed

    private void btnFacultyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacultyMouseEntered
        btnFaculty.setBorderPainted(true);
    }//GEN-LAST:event_btnFacultyMouseEntered

    private void btnFacultyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacultyMouseExited
        btnFaculty.setBorderPainted(false);
    }//GEN-LAST:event_btnFacultyMouseExited

    private void btnFacultyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacultyMousePressed
        btnFaculty.setContentAreaFilled(true);
    }//GEN-LAST:event_btnFacultyMousePressed

    private void btnFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacultyActionPerformed
        new FacultyView(userSessionID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFacultyActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new Dashboard(userSessionID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        btnBack.setBorderPainted(true);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        btnBack.setBorderPainted(false);
    }//GEN-LAST:event_btnBackMouseExited

    private void btnBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMousePressed
        btnBack.setContentAreaFilled(true);
    }//GEN-LAST:event_btnBackMousePressed

    private void btnCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseMouseEntered
        btnCourse.setBorderPainted(true);
    }//GEN-LAST:event_btnCourseMouseEntered

    private void btnCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseMouseExited
        btnCourse.setBorderPainted(false);
    }//GEN-LAST:event_btnCourseMouseExited

    private void btnCourseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseMousePressed
        btnCourse.setContentAreaFilled(true);
    }//GEN-LAST:event_btnCourseMousePressed

    private void btnCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseActionPerformed
        new CourseView(userSessionID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCourseActionPerformed

    private void btnCollegeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCollegeMouseEntered
        btnCollege.setBorderPainted(true);
    }//GEN-LAST:event_btnCollegeMouseEntered

    private void btnCollegeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCollegeMouseExited
        btnCollege.setBorderPainted(false);
    }//GEN-LAST:event_btnCollegeMouseExited

    private void btnCollegeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCollegeMousePressed
        btnCollege.setContentAreaFilled(true);
    }//GEN-LAST:event_btnCollegeMousePressed

    private void btnCollegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCollegeActionPerformed
        new CollegeView(userSessionID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCollegeActionPerformed

    private void btnCourseSubjectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseSubjectMouseEntered
        btnCourseSubject.setBorderPainted(true);
    }//GEN-LAST:event_btnCourseSubjectMouseEntered

    private void btnCourseSubjectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseSubjectMouseExited
        btnCourseSubject.setBorderPainted(false);
    }//GEN-LAST:event_btnCourseSubjectMouseExited

    private void btnCourseSubjectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseSubjectMousePressed
        btnCourseSubject.setContentAreaFilled(true);
    }//GEN-LAST:event_btnCourseSubjectMousePressed

    private void btnCourseSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseSubjectActionPerformed
        new CourseSubjectView(userSessionID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCourseSubjectActionPerformed

    private void btnEnrolledSubjectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnrolledSubjectMouseEntered
        btnEnrolledSubject.setBorderPainted(true);
    }//GEN-LAST:event_btnEnrolledSubjectMouseEntered

    private void btnEnrolledSubjectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnrolledSubjectMouseExited
        btnEnrolledSubject.setBorderPainted(false);
    }//GEN-LAST:event_btnEnrolledSubjectMouseExited

    private void btnEnrolledSubjectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnrolledSubjectMousePressed
        btnEnrolledSubject.setContentAreaFilled(true);
    }//GEN-LAST:event_btnEnrolledSubjectMousePressed

    private void btnEnrolledSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrolledSubjectActionPerformed
        new EnrolledSubjectView(userSessionID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEnrolledSubjectActionPerformed

    private void btnLogsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogsMouseReleased
        btnLogs.setContentAreaFilled(false);
    }//GEN-LAST:event_btnLogsMouseReleased

    private void btnFacultyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacultyMouseReleased
        btnFaculty.setContentAreaFilled(false);
    }//GEN-LAST:event_btnFacultyMouseReleased

    private void btnCourseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseMouseReleased
        btnCourse.setContentAreaFilled(false);
    }//GEN-LAST:event_btnCourseMouseReleased

    private void btnCollegeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCollegeMouseReleased
        btnCollege.setContentAreaFilled(false);
    }//GEN-LAST:event_btnCollegeMouseReleased

    private void btnEnrolledSubjectMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnrolledSubjectMouseReleased
        btnEnrolledSubject.setContentAreaFilled(false);
    }//GEN-LAST:event_btnEnrolledSubjectMouseReleased

    private void btnCourseSubjectMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseSubjectMouseReleased
        btnCourseSubject.setContentAreaFilled(false);
    }//GEN-LAST:event_btnCourseSubjectMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard(userSessionID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmins;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCollege;
    private javax.swing.JButton btnCourse;
    private javax.swing.JButton btnCourseSubject;
    private javax.swing.JButton btnEnrolledSubject;
    private javax.swing.JButton btnFaculty;
    private javax.swing.JButton btnLogs;
    private javax.swing.JButton btnStudents;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
