package Admin;


import Admin.AdminFunctions.AdminInformation;
import Home.Dashboard;
import java.awt.Cursor;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author acer
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form admin0
     */
    static int userSessionID;
    
    public AdminDashboard(int userSessionID) {
        initComponents();
        this.userSessionID = userSessionID;
        {
            btnBack.setOpaque(false); // Make the button transparent
            btnBack.setContentAreaFilled(false); // Don't fill the button area with background
            btnBack.setBorderPainted(false); // Remove the default button border
            btnBack.setFocusPainted(false); // Remove focus border
            btnBack.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Set cursor
        }
        {
            btnAdmins.setOpaque(false); // Make the button transparent
            btnAdmins.setContentAreaFilled(false); // Don't fill the button area with background
            btnAdmins.setBorderPainted(false); // Remove the default button border
            btnAdmins.setFocusPainted(false); // Remove focus border
            btnAdmins.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Set cursor
        }
        {
            btnStudents.setOpaque(false); // Make the button transparent
            btnStudents.setContentAreaFilled(false); // Don't fill the button area with background
            btnStudents.setBorderPainted(false); // Remove the default button border
            btnStudents.setFocusPainted(false); // Remove focus border
            btnStudents.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Set cursor
        }
        {
            btnLogs.setOpaque(false); // Make the button transparent
            btnLogs.setContentAreaFilled(false); // Don't fill the button area with background
            btnLogs.setBorderPainted(false); // Remove the default button border
            btnLogs.setFocusPainted(false); // Remove focus border
            btnLogs.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Set cursor
        }
        {
            btnSubjects.setOpaque(false); // Make the button transparent
            btnSubjects.setContentAreaFilled(false); // Don't fill the button area with background
            btnSubjects.setBorderPainted(false); // Remove the default button border
            btnSubjects.setFocusPainted(false); // Remove focus border
            btnSubjects.setCursor(new Cursor(Cursor.HAND_CURSOR)); // Set cursor
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnAdmins = new javax.swing.JButton();
        btnStudents = new javax.swing.JButton();
        btnLogs = new javax.swing.JButton();
        btnSubjects = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackMousePressed(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 73, 30, 30));

        btnAdmins.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        btnAdmins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdminsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdminsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAdminsMousePressed(evt);
            }
        });
        btnAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminsActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdmins, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 145, 203, 220));

        btnStudents.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        btnStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStudentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStudentsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnStudentsMousePressed(evt);
            }
        });
        btnStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentsActionPerformed(evt);
            }
        });
        getContentPane().add(btnStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 145, 203, 220));

        btnLogs.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        btnLogs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLogsMousePressed(evt);
            }
        });
        btnLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogsActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 145, 203, 220));

        btnSubjects.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));
        btnSubjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubjectsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubjectsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSubjectsMousePressed(evt);
            }
        });
        btnSubjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubjectsActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubjects, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 150, 171, 185));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg_AdminDashboard.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminsActionPerformed
        new AdminInformation(userSessionID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdminsActionPerformed

    private void btnAdminsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminsMouseEntered
        btnAdmins.setBorderPainted(true);
    }//GEN-LAST:event_btnAdminsMouseEntered

    private void btnAdminsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminsMouseExited
        btnAdmins.setBorderPainted(false);
    }//GEN-LAST:event_btnAdminsMouseExited

    private void btnAdminsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdminsMousePressed
        btnAdmins.setContentAreaFilled(true);
    }//GEN-LAST:event_btnAdminsMousePressed

    private void btnStudentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentsMouseEntered
        btnStudents.setBorderPainted(true);
    }//GEN-LAST:event_btnStudentsMouseEntered

    private void btnStudentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentsMouseExited
        btnStudents.setBorderPainted(false);
    }//GEN-LAST:event_btnStudentsMouseExited

    private void btnStudentsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentsMousePressed
        btnStudents.setContentAreaFilled(true);
    }//GEN-LAST:event_btnStudentsMousePressed

    private void btnStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentsActionPerformed
        new StudentInformation(userSessionID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStudentsActionPerformed

    private void btnLogsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogsMouseEntered
        btnLogs.setBorderPainted(true);
    }//GEN-LAST:event_btnLogsMouseEntered

    private void btnLogsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogsMouseExited
        btnLogs.setBorderPainted(false);
    }//GEN-LAST:event_btnLogsMouseExited

    private void btnLogsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogsMousePressed
        btnLogs.setContentAreaFilled(true);
    }//GEN-LAST:event_btnLogsMousePressed

    private void btnLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogsActionPerformed

    private void btnSubjectsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubjectsMouseEntered
        btnSubjects.setBorderPainted(true);
    }//GEN-LAST:event_btnSubjectsMouseEntered

    private void btnSubjectsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubjectsMouseExited
        btnSubjects.setBorderPainted(false);
    }//GEN-LAST:event_btnSubjectsMouseExited

    private void btnSubjectsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubjectsMousePressed
        btnSubjects.setContentAreaFilled(true);
    }//GEN-LAST:event_btnSubjectsMousePressed

    private void btnSubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubjectsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubjectsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new Dashboard(userSessionID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        btnBack.setBorderPainted(true);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        btnBack.setBorderPainted(false);
    }//GEN-LAST:event_btnBackMouseExited

    private void btnBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMousePressed
        btnBack.setContentAreaFilled(true);
    }//GEN-LAST:event_btnBackMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard(userSessionID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmins;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogs;
    private javax.swing.JButton btnStudents;
    private javax.swing.JButton btnSubjects;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
